config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates_presence_of :title, :description #makes sure that the presense of a title and description exists, fails if they do not exist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit create destroy]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>Cs3300</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    </head>

  <body>
  
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      
      <ul class="navbar-nav">
        <a class="navbar-brand" href="#">David&#8217s Portfolio Website</a>
        <li class="nav-item active">
          <% if user_signed_in? %>
            <%= link_to "Home", projects_path, class: 'nav-link' %>
          <% else %>
            <%= link_to "Home", projects_path, class: 'nav-link' %>
          <% end %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <p class="navbar-text float-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link'  %> |
            <button type="button" class="btn btn-danger btn-sm"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></button>
          <% else %>
          <button type="button" class="btn btn-primary btn-sm"><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></button> |
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> 
          <% end %>
        </p>
      </ul>
    </nav>
  

</p>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1 style="color: purple">Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<style>
  body{ background-color:white;}
  h1{
    position: relative;
    left: 15px;
    color: purple;
  }
  h2{
    position: relative;
    left: 650px;
  }
  p{
    position: relative;
    left: 15px;
  }
  h5{
    position:relative;
    left:15px;
  }
  
</style>

<div class="jumbotron jumbotron-fluid">

    <h1>Welcome!</h1>
    <p>I am David and this is my portfolio website! I am a Computer Science major at the University of Colorado Colorado Springs<p>
    <p>This is a showcase of various projects from UCCS.<p>
  
</div>
<div class="container">
<body>
<h1>Projects</h1>
<br>
<h5><table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><br><%= project.title %></td>
        <td><br><%= project.description %></td>
        <td><br><button type="button" class="btn btn-outline-secondary btn-sm"><%= link_to 'Show', project %></button></td>
        <td><br><button type="button" class="btn btn-outline-success btn-sm"><%= link_to 'Edit', edit_project_path(project) %></button</td>
        <td><br><button type="button" class="btn btn-outline-danger btn-sm"><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
        </tr>

    <% end %>
    
  </tbody>
</table></h5>

<br>

<h5><button type="button" class="btn btn-outline-primary btn-sm"><%= link_to 'New Project', new_project_path %></button></h5>
<body>
</div>

app/views/projects/new.html.erb
<h1 style="color: purple">New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <h1 style = "color: purple; font-family: arial"><strong>Title:</strong>
  <%= @project.title %></h1>
</p>

<p>
  <h6><strong>Description:</strong>
  <%= @project.description %><h6>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>